#!/bin/sh

if test -r Makefile; then
    echo >&2 "***********************************"
    echo >&2 "** make everything real tidy :-) **"
    echo >&2 "**  Ignore any errors from make  **"
    echo >&2 "***********************************"
    make -k maintainer-clean
fi

(
    echo >&2 "****************************************"
    echo >&2 "** auto-generating data Makefile.am's **"
    echo >&2 "****************************************"
    cd data && ./genMakefileAM 
)

echo >&2 "***********************************"
echo >&2 "** basic autoconf/automake setup **"
echo >&2 "***********************************"
aclocal
autoheader
autoconf
automake -a

echo >&2 "*******************************************"
echo >&2 "** special setup for package maintenance **"
echo >&2 "*******************************************"
mkdir -p bin
rm -f bin/nighthawk && \
  ln -s ../src/nighthawk bin/nighthawk

mkdir -p libexec
rm -f libexec/nighthawk_sound && \
  ln -s ../src_sound/nighthawk_sound libexec/nighthawk_sound

mkdir -p share/nighthawk
rm -f share/nighthawk/data && \
  ln -s ../../data share/nighthawk/data

echo >&2 "*******************************************"
echo >&2 "** special configuration for maintenance **"
echo >&2 "*******************************************"
./configure --prefix=`pwd` --enable-tools --with-scores='/tmp/.nighthawk.scores' ${1+"$@"}

